<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'Home::index');
$routes->get('login', 'AuthController::login', ['filter' => 'guest']);
$routes->post('login', 'AuthController::attemptLogin', ['filter' => 'guest']);
$routes->get('forgot-password', 'AuthController::forgotPassword', ['filter' => 'guest']);
$routes->post('forgot-password', 'AuthController::sendResetLink', ['filter' => 'guest']);
$routes->get('reset-password/(:segment)/(:segment)', 'AuthController::resetPassword/$1/$2', ['filter' => 'guest']);
$routes->post('reset-password/(:segment)/(:segment)', 'AuthController::updatePassword/$1/$2', ['filter' => 'guest']);
$routes->get('logout', 'AuthController::logout', ['filter' => 'auth']);

$routes->group('', ['filter' => 'auth'], static function (RouteCollection $routes): void {
    $routes->get('dashboard', 'DashboardController::index', ['filter' => 'permission:dashboard.view']);
    $routes->get('dashboard/readiness', 'DashboardController::readiness', ['filter' => 'permission:dashboard.view']);
    $routes->get('dashboard/qa', 'DashboardController::qa', ['filter' => 'permission:dashboard.view']);
    $routes->post('dashboard/qa/runs', 'DashboardController::storeQaRun', ['filter' => 'permission:dashboard.view']);
    $routes->get('sistemas', 'SystemsController::index', ['filter' => 'permission:systems.view']);
    $routes->get('sistemas/nuevo', 'SystemsController::create', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas', 'SystemsController::store', ['filter' => 'permission:systems.manage']);
    $routes->get('sistemas/(:segment)/editar', 'SystemsController::edit/$1', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/(:segment)/actualizar', 'SystemsController::update/$1', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/(:segment)/toggle', 'SystemsController::toggle/$1', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/(:segment)/eliminar', 'SystemsController::delete/$1', ['filter' => 'permission:systems.manage']);
    $routes->get('sistemas/asignaciones-empresa/nueva', 'SystemsController::createCompanyAssignmentForm', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/asignaciones-empresa', 'SystemsController::storeCompanyAssignment', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/asignaciones-empresa/(:segment)/toggle', 'SystemsController::toggleCompanyAssignment/$1', ['filter' => 'permission:systems.manage']);
    $routes->get('sistemas/asignaciones-usuario/nueva', 'SystemsController::createUserAssignmentForm', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/asignaciones-usuario', 'SystemsController::storeUserAssignment', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/asignaciones-usuario/(:segment)/toggle', 'SystemsController::toggleUserAssignment/$1', ['filter' => 'permission:systems.manage']);
    $routes->get('sistemas/usuarios/(:segment)/detalle', 'SystemsController::userDetail/$1', ['filter' => 'permission:systems.manage']);
    $routes->post('sistemas/usuarios/(:segment)/toggle', 'SystemsController::toggleUserPermissions/$1', ['filter' => 'permission:systems.manage']);

    $routes->get('inventario', 'InventoryController::index', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/configuracion', 'InventoryController::configuration', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/kardex', 'InventoryController::kardex', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/kardex/pdf', 'InventoryController::kardexPdf', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/kardex/productos/(:segment)/detalle', 'InventoryController::kardexDetail/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/kardex/productos/(:segment)/movimientos-pdf', 'InventoryController::kardexProductPdf/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/configuracion/parametros/editar', 'InventoryController::editSettingsForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/configuracion/parametros', 'InventoryController::updateSettings', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/depositos/nuevo', 'InventoryController::createWarehouseForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/depositos', 'InventoryController::storeWarehouse', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/depositos/(:segment)/editar', 'InventoryController::editWarehouseForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/depositos/(:segment)/actualizar', 'InventoryController::updateWarehouse/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/depositos/(:segment)/toggle', 'InventoryController::toggleWarehouse/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/depositos/(:segment)/eliminar', 'InventoryController::deleteWarehouse/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/ubicaciones/nueva', 'InventoryController::createLocationForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/ubicaciones', 'InventoryController::storeLocation', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/ubicaciones/(:segment)/editar', 'InventoryController::editLocationForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/ubicaciones/(:segment)/actualizar', 'InventoryController::updateLocation/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/ubicaciones/(:segment)/toggle', 'InventoryController::toggleLocation/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/ubicaciones/(:segment)/eliminar', 'InventoryController::deleteLocation/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/productos/nuevo', 'InventoryController::createProductForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/productos', 'InventoryController::storeProduct', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/productos/(:segment)/editar', 'InventoryController::editProductForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/productos/(:segment)/actualizar', 'InventoryController::updateProduct/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/productos/(:segment)/toggle', 'InventoryController::toggleProduct/$1', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/productos/(:segment)/eliminar', 'InventoryController::deleteProduct/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/productos/(:segment)/trazabilidad', 'InventoryController::productTraceability/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/productos/(:segment)/pdf', 'InventoryController::productPdf/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/productos/(:segment)/trazabilidad-pdf', 'InventoryController::productTraceabilityPdf/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/movimientos/nuevo', 'InventoryController::createMovementForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/movimientos', 'InventoryController::storeMovement', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/reservas/nueva', 'InventoryController::createReservationForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/reservas', 'InventoryController::storeReservation', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/reservas/(:segment)/liberar', 'InventoryController::releaseReservation/$1', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/ensambles/nuevo', 'InventoryController::createAssemblyForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/ensambles', 'InventoryController::storeAssembly', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/cierres/nuevo', 'InventoryController::createClosureForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/cierres', 'InventoryController::storeClosure', ['filter' => 'permission:systems.view']);
    $routes->get('inventario/revalorizaciones/nueva', 'InventoryController::createRevaluationForm', ['filter' => 'permission:systems.view']);
    $routes->post('inventario/revalorizaciones', 'InventoryController::storeRevaluation', ['filter' => 'permission:systems.view']);
    $routes->get('ventas', 'SalesController::index', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/diarios', 'SalesController::daily', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/pos', 'SalesController::pos', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/pos', 'SalesController::storePos', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/kiosco', 'SalesController::kiosk', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/kiosco', 'SalesController::storeKiosk', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/reportes', 'SalesController::reports', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/reportes/csv', 'SalesController::reportsCsv', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/reportes/pdf', 'SalesController::reportsPdf', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/cobranzas', 'SalesController::receivables', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/cobranzas/nuevo', 'SalesController::createReceiptForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/cobranzas', 'SalesController::storeReceipt', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/cobranzas/(:segment)/detalle', 'SalesController::receiptDetail/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/cobranzas/(:segment)/anular', 'SalesController::voidReceipt/$1', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/configuracion', 'SalesController::configuration', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/configuracion/editar', 'SalesController::editSettingsForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/configuracion', 'SalesController::updateSettings', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/dispositivos/nuevo', 'SalesController::createDeviceForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/dispositivos', 'SalesController::storeDevice', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/arca/diagnostico', 'SalesController::diagnoseArca', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/arca/test', 'SalesController::testArcaConnection', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/vendedores/nuevo', 'SalesController::createAgentForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/vendedores', 'SalesController::storeAgent', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/zonas/nueva', 'SalesController::createZoneForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/zonas', 'SalesController::storeZone', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/condiciones/nueva', 'SalesController::createConditionForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/condiciones', 'SalesController::storeCondition', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/listas-precio/nueva', 'SalesController::createPriceListForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/listas-precio', 'SalesController::storePriceList', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/promociones/nueva', 'SalesController::createPromotionForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/promociones', 'SalesController::storePromotion', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/clientes/nuevo', 'SalesController::createCustomerForm', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/clientes', 'SalesController::storeCustomer', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/nueva', 'SalesController::create', ['filter' => 'permission:systems.view']);
    $routes->post('ventas', 'SalesController::store', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/(:segment)/editar', 'SalesController::edit/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/actualizar', 'SalesController::update/$1', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/(:segment)/convertir/(:segment)', 'SalesController::convert/$1/$2', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/confirmar', 'SalesController::confirm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/cancelar', 'SalesController::cancel/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/arca/autorizar', 'SalesController::authorizeArca/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/arca/consultar', 'SalesController::consultArca/$1', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/(:segment)/devolucion', 'SalesController::createReturnForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('ventas/(:segment)/devolucion', 'SalesController::storeReturn/$1', ['filter' => 'permission:systems.view']);
    $routes->get('ventas/(:segment)/pdf', 'SalesController::pdf/$1', ['filter' => 'permission:systems.view']);
    $routes->get('compras', 'PurchasesController::index', ['filter' => 'permission:systems.view']);
    $routes->get('compras/proveedores/nuevo', 'PurchasesController::createSupplierForm', ['filter' => 'permission:systems.view']);
    $routes->post('compras/proveedores', 'PurchasesController::storeSupplier', ['filter' => 'permission:systems.view']);
    $routes->get('compras/ordenes/nueva', 'PurchasesController::createOrderForm', ['filter' => 'permission:systems.view']);
    $routes->post('compras/ordenes', 'PurchasesController::storeOrder', ['filter' => 'permission:systems.view']);
    $routes->post('compras/ordenes/(:segment)/confirmar', 'PurchasesController::confirmOrder/$1', ['filter' => 'permission:systems.view']);
    $routes->get('compras/ordenes/(:segment)/recepcionar', 'PurchasesController::createReceiptForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('compras/recepciones', 'PurchasesController::storeReceipt', ['filter' => 'permission:systems.view']);
    $routes->get('compras/facturas/nueva', 'PurchasesController::createInvoiceForm', ['filter' => 'permission:systems.view']);
    $routes->post('compras/facturas', 'PurchasesController::storeInvoice', ['filter' => 'permission:systems.view']);
    $routes->get('compras/notas-credito/nueva', 'PurchasesController::createCreditNoteForm', ['filter' => 'permission:systems.view']);
    $routes->post('compras/notas-credito', 'PurchasesController::storeCreditNote', ['filter' => 'permission:systems.view']);
    $routes->get('compras/recepciones/(:segment)/devolver', 'PurchasesController::createReturnForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('compras/devoluciones', 'PurchasesController::storeReturn', ['filter' => 'permission:systems.view']);
    $routes->get('compras/cuentas/(:segment)/pagar', 'PurchasesController::createPaymentForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('compras/pagos', 'PurchasesController::storePayment', ['filter' => 'permission:systems.view']);
    $routes->get('caja', 'CashController::index', ['filter' => 'permission:systems.view']);
    $routes->get('caja/sesiones/apertura/nueva', 'CashController::openSessionForm', ['filter' => 'permission:systems.view']);
    $routes->post('caja/sesiones/apertura', 'CashController::storeOpenSession', ['filter' => 'permission:systems.view']);
    $routes->get('caja/sesiones/(:segment)/cierre', 'CashController::closeSessionForm/$1', ['filter' => 'permission:systems.view']);
    $routes->post('caja/sesiones/(:segment)/cierre', 'CashController::storeCloseSession/$1', ['filter' => 'permission:systems.view']);
    $routes->get('caja/movimientos/nuevo', 'CashController::createMovementForm', ['filter' => 'permission:systems.view']);
    $routes->post('caja/movimientos', 'CashController::storeMovement', ['filter' => 'permission:systems.view']);
    $routes->get('caja/cheques/nuevo', 'CashController::createCheckForm', ['filter' => 'permission:systems.view']);
    $routes->post('caja/cheques', 'CashController::storeCheck', ['filter' => 'permission:systems.view']);
    $routes->get('caja/conciliaciones/nueva', 'CashController::createReconciliationForm', ['filter' => 'permission:systems.view']);
    $routes->post('caja/conciliaciones', 'CashController::storeReconciliation', ['filter' => 'permission:systems.view']);

    $routes->get('usuarios', 'UsersController::index', ['filter' => 'permission:users.view']);
    $routes->get('usuarios/nuevo', 'UsersController::create', ['filter' => 'permission:users.manage']);
    $routes->post('usuarios', 'UsersController::store', ['filter' => 'permission:users.manage']);
    $routes->get('usuarios/(:segment)/editar', 'UsersController::edit/$1', ['filter' => 'permission:users.manage']);
    $routes->post('usuarios/(:segment)/actualizar', 'UsersController::update/$1', ['filter' => 'permission:users.manage']);
    $routes->post('usuarios/(:segment)/toggle', 'UsersController::toggle/$1', ['filter' => 'permission:users.manage']);
    $routes->post('usuarios/(:segment)/eliminar', 'UsersController::delete/$1', ['filter' => 'permission:users.manage']);

    $routes->get('empresas', 'CompaniesController::index', ['filter' => 'permission:companies.view']);
    $routes->get('empresas/nueva', 'CompaniesController::create', ['filter' => 'permission:companies.manage']);
    $routes->post('empresas', 'CompaniesController::store', ['filter' => 'permission:companies.manage']);
    $routes->get('empresas/(:segment)/editar', 'CompaniesController::edit/$1', ['filter' => 'permission:companies.view']);
    $routes->post('empresas/(:segment)/actualizar', 'CompaniesController::update/$1', ['filter' => 'permission:companies.view']);
    $routes->post('empresas/(:segment)/toggle', 'CompaniesController::toggle/$1', ['filter' => 'permission:companies.manage']);
    $routes->post('empresas/(:segment)/eliminar', 'CompaniesController::delete/$1', ['filter' => 'permission:companies.manage']);

    $routes->get('configuracion', 'SettingsController::index', ['filter' => 'permission:settings.view']);
    $routes->get('configuracion/empresa/editar', 'SettingsController::editCompanyForm', ['filter' => 'permission:settings.manage']);
    $routes->get('configuracion/sucursales/nueva', 'SettingsController::createBranchForm', ['filter' => 'permission:branches.manage']);
    $routes->get('configuracion/impuestos/nuevo', 'SettingsController::createTaxForm', ['filter' => 'permission:taxes.manage']);
    $routes->get('configuracion/monedas/nueva', 'SettingsController::createCurrencyForm', ['filter' => 'permission:currencies.manage']);
    $routes->get('configuracion/numeraciones/nueva', 'SettingsController::createVoucherSequenceForm', ['filter' => 'permission:voucher_sequences.manage']);
    $routes->post('configuracion/empresa', 'SettingsController::updateCompany', ['filter' => 'permission:settings.manage']);
    $routes->post('configuracion/sucursales', 'SettingsController::storeBranch', ['filter' => 'permission:branches.manage']);
    $routes->post('configuracion/impuestos', 'SettingsController::storeTax', ['filter' => 'permission:taxes.manage']);
    $routes->post('configuracion/monedas', 'SettingsController::storeCurrency', ['filter' => 'permission:currencies.manage']);
    $routes->post('configuracion/numeraciones', 'SettingsController::storeVoucherSequence', ['filter' => 'permission:voucher_sequences.manage']);
});

$routes->group('api/v1', ['namespace' => 'App\Controllers\Api\V1'], static function (RouteCollection $routes): void {
    $routes->get('health', 'HealthController::index');
    $routes->post('auth/login', 'AuthController::login');
    $routes->post('auth/forgot-password', 'AuthController::forgotPassword');
    $routes->post('auth/reset-password', 'AuthController::resetPassword');
    $routes->post('auth/refresh', 'AuthController::refresh');

    $routes->get('auth/me', 'AuthController::me', ['filter' => 'apiauth']);
    $routes->post('auth/logout', 'AuthController::logout', ['filter' => 'apiauth']);

    // 2FA endpoints (require authentication)
    $routes->post('auth/2fa/setup', 'AuthController::twoFactorSetup', ['filter' => 'apiauth']);
    $routes->post('auth/2fa/confirm', 'AuthController::twoFactorConfirm', ['filter' => 'apiauth']);
    $routes->post('auth/2fa/disable', 'AuthController::twoFactorDisable', ['filter' => 'apiauth']);

    $routes->get('dashboard', 'DashboardController::index', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('dashboard/readiness', 'DashboardController::readiness', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('dashboard/qa', 'DashboardController::qa', ['filter' => 'apipermission:dashboard.view']);
    $routes->post('dashboard/qa', 'DashboardController::storeQaRun', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('systems', 'SystemsController::index', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory', 'InventoryController::index', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/settings', 'InventoryController::settings', ['filter' => 'apipermission:systems.view']);
    $routes->put('inventory/settings', 'InventoryController::updateSettings', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/warehouses', 'InventoryController::warehouses', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/warehouses', 'InventoryController::storeWarehouse', ['filter' => 'apipermission:systems.view']);
    $routes->put('inventory/warehouses/(:segment)', 'InventoryController::updateWarehouse/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/warehouses/(:segment)/toggle', 'InventoryController::toggleWarehouse/$1', ['filter' => 'apipermission:systems.view']);
    $routes->delete('inventory/warehouses/(:segment)', 'InventoryController::deleteWarehouse/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/locations', 'InventoryController::locations', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/locations', 'InventoryController::storeLocation', ['filter' => 'apipermission:systems.view']);
    $routes->put('inventory/locations/(:segment)', 'InventoryController::updateLocation/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/locations/(:segment)/toggle', 'InventoryController::toggleLocation/$1', ['filter' => 'apipermission:systems.view']);
    $routes->delete('inventory/locations/(:segment)', 'InventoryController::deleteLocation/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/products', 'InventoryController::products', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/products', 'InventoryController::storeProduct', ['filter' => 'apipermission:systems.view']);
    $routes->put('inventory/products/(:segment)', 'InventoryController::updateProduct/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/products/(:segment)/toggle', 'InventoryController::toggleProduct/$1', ['filter' => 'apipermission:systems.view']);
    $routes->delete('inventory/products/(:segment)', 'InventoryController::deleteProduct/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/products/(:segment)/traceability', 'InventoryController::traceability/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/movements', 'InventoryController::movements', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/movements', 'InventoryController::storeMovement', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/reservations', 'InventoryController::reservations', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/reservations', 'InventoryController::storeReservation', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/reservations/(:segment)/release', 'InventoryController::releaseReservation/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/assemblies', 'InventoryController::storeAssembly', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/period-closures', 'InventoryController::storeClosure', ['filter' => 'apipermission:systems.view']);
    $routes->post('inventory/revaluations', 'InventoryController::storeRevaluation', ['filter' => 'apipermission:systems.view']);
    $routes->get('inventory/kardex', 'InventoryController::kardex', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales', 'SalesController::index', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/pos-catalog', 'SalesController::posCatalog', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/reports', 'SalesController::reports', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/reports/export', 'SalesController::reportsExport', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/receivables', 'SalesController::receivables', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/receipts', 'SalesController::receipts', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/commissions', 'SalesController::commissions', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/settings', 'SalesController::settings', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/devices', 'SalesController::devices', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/arca/status', 'SalesController::arcaStatus', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/arca/events', 'SalesController::arcaEvents', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/arca/diagnostics', 'SalesController::arcaDiagnostics', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/document-types', 'SalesController::documentTypes', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/points-of-sale', 'SalesController::pointsOfSale', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/agents', 'SalesController::agents', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/agents', 'SalesController::storeAgent', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/zones', 'SalesController::zones', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/zones', 'SalesController::storeZone', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/conditions', 'SalesController::conditions', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/conditions', 'SalesController::storeCondition', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/audit', 'SalesController::audit', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/customers', 'SalesController::customers', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/price-lists', 'SalesController::priceLists', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/promotions', 'SalesController::promotions', ['filter' => 'apipermission:systems.view']);
    $routes->get('sales/(:segment)', 'SalesController::show/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/customers', 'SalesController::storeCustomer', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/price-lists', 'SalesController::storePriceList', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/promotions', 'SalesController::storePromotion', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/receipts', 'SalesController::storeReceipt', ['filter' => 'apipermission:systems.view']);
    $routes->put('sales/settings', 'SalesController::updateSettings', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/devices', 'SalesController::storeDevice', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/arca/test-auth', 'SalesController::testArcaConnection', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales', 'SalesController::store', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/pos', 'SalesController::storePos', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/kiosk', 'SalesController::storeKiosk', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/convert/(:segment)', 'SalesController::convert/$1/$2', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/confirm', 'SalesController::confirm/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/cancel', 'SalesController::cancel/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/arca/authorize', 'SalesController::authorizeArca/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/arca/consult', 'SalesController::consultArca/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('sales/(:segment)/return', 'SalesController::storeReturn/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases', 'PurchasesController::index', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/suppliers', 'PurchasesController::suppliers', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/suppliers', 'PurchasesController::storeSupplier', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/orders', 'PurchasesController::orders', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/orders', 'PurchasesController::storeOrder', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/orders/(:segment)/confirm', 'PurchasesController::confirmOrder/$1', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/receipts', 'PurchasesController::receipts', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/receipts', 'PurchasesController::storeReceipt', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/invoices', 'PurchasesController::invoices', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/invoices', 'PurchasesController::storeInvoice', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/credit-notes', 'PurchasesController::creditNotes', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/credit-notes', 'PurchasesController::storeCreditNote', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/returns', 'PurchasesController::storeReturn', ['filter' => 'apipermission:systems.view']);
    $routes->get('purchases/payables', 'PurchasesController::payables', ['filter' => 'apipermission:systems.view']);
    $routes->post('purchases/payments', 'PurchasesController::storePayment', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash', 'CashController::index', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash/registers', 'CashController::registers', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash/sessions', 'CashController::sessions', ['filter' => 'apipermission:systems.view']);
    $routes->post('cash/sessions/open', 'CashController::openSession', ['filter' => 'apipermission:systems.view']);
    $routes->post('cash/sessions/(:segment)/close', 'CashController::closeSession/$1', ['filter' => 'apipermission:systems.view']);
    $routes->post('cash/movements', 'CashController::storeMovement', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash/gateways', 'CashController::gateways', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash/checks', 'CashController::checks', ['filter' => 'apipermission:systems.view']);
    $routes->post('cash/checks', 'CashController::storeCheck', ['filter' => 'apipermission:systems.view']);
    $routes->get('cash/reconciliations', 'CashController::reconciliations', ['filter' => 'apipermission:systems.view']);
    $routes->post('cash/reconciliations', 'CashController::storeReconciliation', ['filter' => 'apipermission:systems.view']);
    $routes->post('systems', 'SystemsController::store', ['filter' => 'apipermission:systems.manage']);
    $routes->put('systems/(:segment)', 'SystemsController::update/$1', ['filter' => 'apipermission:systems.manage']);
    $routes->post('systems/(:segment)/toggle', 'SystemsController::toggle/$1', ['filter' => 'apipermission:systems.manage']);
    $routes->delete('systems/(:segment)', 'SystemsController::delete/$1', ['filter' => 'apipermission:systems.manage']);
    $routes->post('systems/company-assignments', 'SystemsController::storeCompanyAssignment', ['filter' => 'apipermission:systems.manage']);
    $routes->post('systems/company-assignments/(:segment)/toggle', 'SystemsController::toggleCompanyAssignment/$1', ['filter' => 'apipermission:systems.manage']);
    $routes->post('systems/user-assignments', 'SystemsController::storeUserAssignment', ['filter' => 'apipermission:systems.manage']);
    $routes->post('systems/user-assignments/(:segment)/toggle', 'SystemsController::toggleUserAssignment/$1', ['filter' => 'apipermission:systems.manage']);

    $routes->get('users', 'UsersController::index', ['filter' => 'apipermission:users.view']);
    $routes->post('users', 'UsersController::store', ['filter' => 'apipermission:users.manage']);
    $routes->put('users/(:segment)', 'UsersController::update/$1', ['filter' => 'apipermission:users.manage']);

    $routes->get('companies', 'CompaniesController::index', ['filter' => 'apipermission:companies.view']);
    $routes->post('companies', 'CompaniesController::store', ['filter' => 'apipermission:companies.manage']);
    $routes->put('companies/(:segment)', 'CompaniesController::update/$1', ['filter' => 'apipermission:companies.view']);
    $routes->delete('companies/(:segment)', 'CompaniesController::delete/$1', ['filter' => 'apipermission:companies.manage']);

    $routes->get('settings', 'SettingsController::index', ['filter' => 'apipermission:settings.view']);
    $routes->put('settings/company', 'SettingsController::updateCompany', ['filter' => 'apipermission:settings.manage']);
    $routes->post('settings/branches', 'SettingsController::storeBranch', ['filter' => 'apipermission:branches.manage']);
    $routes->post('settings/taxes', 'SettingsController::storeTax', ['filter' => 'apipermission:taxes.manage']);
    $routes->post('settings/currencies', 'SettingsController::storeCurrency', ['filter' => 'apipermission:currencies.manage']);
    $routes->post('settings/voucher-sequences', 'SettingsController::storeVoucherSequence', ['filter' => 'apipermission:voucher_sequences.manage']);

    // ── Accounting (Phase 3) ─────────────────────────────
    $routes->get('accounting/chart', 'AccountingController::chartOfAccounts', ['filter' => 'apipermission:systems.view']);
    $routes->post('accounting/accounts', 'AccountingController::storeAccount', ['filter' => 'apipermission:systems.manage']);
    $routes->post('accounting/journal-entries', 'AccountingController::storeJournalEntry', ['filter' => 'apipermission:systems.manage']);
    $routes->post('accounting/journal-entries/(:segment)/post', 'AccountingController::postEntry/$1', ['filter' => 'apipermission:systems.manage']);
    $routes->get('accounting/trial-balance', 'AccountingController::trialBalance', ['filter' => 'apipermission:systems.view']);
    $routes->get('accounting/balance-sheet', 'AccountingController::balanceSheet', ['filter' => 'apipermission:systems.view']);
    $routes->get('accounting/income-statement', 'AccountingController::incomeStatement', ['filter' => 'apipermission:systems.view']);
    $routes->get('accounting/ledger/(:segment)', 'AccountingController::accountLedger/$1', ['filter' => 'apipermission:systems.view']);

    // ── Business Intelligence (Phase 5) ──────────────────
    $routes->get('bi/executive', 'BiController::executive', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('bi/forecast', 'BiController::forecast', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('bi/cash-flow', 'BiController::cashFlow', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('bi/alerts', 'BiController::alerts', ['filter' => 'apipermission:dashboard.view']);
    $routes->get('bi/libro-iva/ventas', 'BiController::libroIvaVentas', ['filter' => 'apipermission:systems.view']);
    $routes->get('bi/libro-iva/compras', 'BiController::libroIvaCompras', ['filter' => 'apipermission:systems.view']);
    $routes->get('bi/libro-iva/export', 'BiController::exportLibroIva', ['filter' => 'apipermission:systems.view']);

    // ── Codex Assist AI (Phase 6) ────────────────────────
    $routes->post('assist/ask', 'AssistController::ask', ['filter' => 'apiauth']);
    $routes->get('assist/guide/(:segment)', 'AssistController::guide/$1', ['filter' => 'apiauth']);
    $routes->get('assist/alerts', 'AssistController::alerts', ['filter' => 'apiauth']);

    // ── Notifications (Phase 4) ──────────────────────────
    $routes->get('notifications', 'NotificationsController::index', ['filter' => 'apiauth']);
    $routes->post('notifications/(:segment)/read', 'NotificationsController::markRead/$1', ['filter' => 'apiauth']);
    $routes->post('notifications/read-all', 'NotificationsController::markAllRead', ['filter' => 'apiauth']);
});
