<!doctype html><html lang="es"><head><meta charset="utf-8"><title><?= esc($title.' '.$document['number']) ?></title>
<style>@page{margin:15mm}body{font-family:DejaVu Sans,Arial,sans-serif;font-size:12px;color:#18243b;margin:20px}h1{font-size:23px}header{border-bottom:2px solid #253052;padding-bottom:15px}table{width:100%;border-collapse:collapse;table-layout:fixed;margin-top:22px}th,td{padding:9px 6px;border-bottom:1px solid #ddd;overflow-wrap:anywhere;word-wrap:break-word;text-align:left}th{background:#f0f3f8}.right{text-align:right}.notes{white-space:pre-line;margin-top:20px}tr{page-break-inside:avoid}.totals{margin-left:auto;width:55%}</style></head><body>
<header><h1><?= esc($title) ?> <?= esc($document['number']) ?></h1><p><?= esc(($company['legal_name'] ?? '') ?: $company['name']) ?></p><p>CUIT: <?= esc($company['tax_id'] ?? '') ?></p></header>
<p><strong>Cliente:</strong> <?= esc($document['customer_name_snapshot'] ?? '') ?></p>
<p><strong>Fecha:</strong> <?= esc(substr($document['date'],0,10)) ?> · <strong>Estado:</strong> <?= esc($document['status']) ?></p>
<?php foreach (['valid_until'=>'Valido hasta','shipping_address'=>'Direccion de entrega','carrier'=>'Transportista','tracking_number'=>'Seguimiento'] as $key=>$label): ?><?php if (!empty($document[$key])): ?><p><strong><?= esc($label) ?>:</strong> <?= esc($document[$key]) ?></p><?php endif; ?><?php endforeach; ?>
<table><thead><tr><th style="width:15%">Codigo</th><th>Producto</th><th style="width:12%">Cantidad</th><?php if (!$unpriced): ?><th class="right" style="width:18%">Precio unitario</th><th class="right" style="width:18%">Importe</th><?php endif; ?></tr></thead><tbody>
<?php foreach ($items as $item): ?><tr><td><?= esc($item['sku'] ?? '') ?></td><td><?= esc($item['product_name']) ?><?php if (!empty($item['lot_number'])): ?><br>Lote: <?= esc($item['lot_number']) ?><?php endif; ?><?php if (!empty($item['serial_number'])): ?><br>Serie: <?= esc($item['serial_number']) ?><?php endif; ?></td><td><?= number_format((float)$item['quantity'],2,',','.') ?></td><?php if (!$unpriced): ?><td class="right"><?= number_format((float)$item['unit_price'],2,',','.') ?></td><td class="right"><?= number_format((float)$item['line_total'],2,',','.') ?></td><?php endif; ?></tr><?php endforeach; ?>
</tbody></table>
<?php if (!$unpriced): ?><table class="totals"><tr><td>Subtotal neto</td><td class="right"><?= number_format((float)($document['subtotal'] ?? 0),2,',','.') ?></td></tr><tr><td>IVA</td><td class="right"><?= number_format((float)($document['tax_total'] ?? 0),2,',','.') ?></td></tr><tr><td><strong>Total <?= esc($document['currency_code'] ?? 'ARS') ?></strong></td><td class="right"><strong><?= number_format((float)($document['total'] ?? 0),2,',','.') ?></strong></td></tr></table><?php endif; ?>
<?php if (!empty($document['notes'])): ?><p class="notes"><strong>Observaciones:</strong><br><?= esc($document['notes']) ?></p><?php endif; ?>
<?php if ($unpriced): ?><p style="margin-top:50px">Recibido por: ____________________ Firma: ____________________</p><?php endif; ?>
</body></html>
