<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:12px;color:#1f2937}table{width:100%;border-collapse:collapse}th,td{padding:6px;border-bottom:1px solid #ddd;text-align:left}th{background:#f3f4f6}.section{margin-bottom:18px}</style></head><body>
<div class="section"><h1>Reporte de ventas</h1><div><?= esc($company['name'] ?? 'Empresa') ?></div><div>Generado: <?= esc($generatedAt ?? '') ?></div></div>
<div class="section"><table><tr><td><strong>Ventas</strong><br><?= esc((string) $report['summary']['sales_count']) ?></td><td><strong>Facturado</strong><br><?= number_format((float) $report['summary']['gross_total'], 2, ',', '.') ?></td><td><strong>Cobrado</strong><br><?= number_format((float) $report['summary']['paid_total'], 2, ',', '.') ?></td><td><strong>Ticket promedio</strong><br><?= number_format((float) $report['summary']['average_ticket'], 2, ',', '.') ?></td><td><strong>Margen</strong><br><?= number_format((float) ($report['summary']['margin_total'] ?? 0), 2, ',', '.') ?></td></tr></table></div>
<div class="section"><h3>Top productos</h3><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Total</th></tr></thead><tbody><?php foreach ($report['top_products'] as $row): ?><tr><td><?= esc($row['product_name']) ?></td><td><?= number_format((float) $row['qty'], 2, ',', '.') ?></td><td><?= number_format((float) $row['total'], 2, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="section"><h3>Top clientes</h3><table><thead><tr><th>Cliente</th><th>Ventas</th><th>Total</th></tr></thead><tbody><?php foreach ($report['top_customers'] as $row): ?><tr><td><?= esc($row['customer_name']) ?></td><td><?= esc((string) $row['orders_count']) ?></td><td><?= number_format((float) $row['total'], 2, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="section"><h3>Top vendedores</h3><table><thead><tr><th>Vendedor</th><th>Ventas</th><th>Total</th><th>Margen</th></tr></thead><tbody><?php foreach (($report['top_agents'] ?? []) as $row): ?><tr><td><?= esc($row['sales_agent_name']) ?></td><td><?= esc((string) $row['orders_count']) ?></td><td><?= number_format((float) $row['total'], 2, ',', '.') ?></td><td><?= number_format((float) ($row['margin_total'] ?? 0), 2, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="section"><h3>Top zonas</h3><table><thead><tr><th>Zona</th><th>Ventas</th><th>Total</th></tr></thead><tbody><?php foreach (($report['top_zones'] ?? []) as $row): ?><tr><td><?= esc($row['sales_zone_name']) ?></td><td><?= esc((string) $row['orders_count']) ?></td><td><?= number_format((float) $row['total'], 2, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="section"><h3>Canales</h3><table><thead><tr><th>Canal</th><th>Ventas</th><th>Total</th></tr></thead><tbody><?php foreach (($report['channel_mix'] ?? []) as $row): ?><tr><td><?= esc($row['channel_name']) ?></td><td><?= esc((string) $row['orders_count']) ?></td><td><?= number_format((float) $row['total'], 2, ',', '.') ?></td></tr><?php endforeach; ?></tbody></table></div>
</body></html>
